data:
  image: tianon/true
  volumes:
    - /var/lib/mysql
#mysql:
master:
  image: xer0x/triton-mysql
  volumes_from:
    - data
  restart: always
  mem_limit: 1024m
  environment:
    - MYSQL_ROOT_PASSWORD
    - MYSQL_ALLOW_EMPTY_PASSWORD
    - TRITON_MYSQL_ROLE=master
slave:
  image: xer0x/triton-mysql
  links:
    - master
  restart: always
  mem_limit: 1024m
  environment:
    - MYSQL_ROOT_PASSWORD
    - MYSQL_ALLOW_EMPTY_PASSWORD
    - TRITON_MYSQL_ROLE=slave
