data:
  image: tianon/true
  volumes:
    - /var/lib/mysql
#mysql:
master:
  image: xer0x/triton-mysql
  volumes_from:
    - data
  #links:
    #- consul
  #ports:
    #- 8384
  #restart: always
  mem_limit: 1024m
  environment:
    - MYSQL_ROOT_PASSWORD
    - MYSQL_ALLOW_EMPTY_PASSWORD
    - TRITON_MYSQL_ROLE=master
slave:
  image: xer0x/triton-mysql
  #volumes_from:
  #  - data
  #links:
    #- consul
  #ports:
    #- 8384
  #restart: always
  mem_limit: 1024m
  environment:
    - MYSQL_ROOT_PASSWORD
    - MYSQL_ALLOW_EMPTY_PASSWORD
    - TRITON_MYSQL_ROLE=slave
#consul:
  #image: gliderlabs/consul-server
  #command: -bootstrap -ui-dir /ui
  #expose:
  #- 8400
  #- 8500
  #- 53/udp
  #restart: always
  #mem_limit: 256m
#cloner:
#  image: xer0x/triton-mysql-cloner
#  volumes_from:
#    - data
#  links:
#    - mysql
#  entrypoint:
#    #- "top"
#    #- "sh -c 'while [ 1 ]; do sleep 60; done'"
#    # - "/start.sh"
#    #- "sleep 999999999"
#  environment:
#    - MYSQL_ROOT_PASSWORD
#    - MYSQL_ALLOW_EMPTY_PASSWORD

# WHAT IF:
#
# mysql-slave:
#   image: triton-mysql
#   environment:
#     triton_mysql_mode: master
# mysql-master:
#   image: triton-mysql
#   environment:
#     triton_mysql_mode: master
#
# MySQL 5.7 supports multi-master, but <5.7 is only single master
