data:
  image: tianon/true
  volumes:
    - /var/lib/mysql
mysql:
  image: mysql:5.6
  volumes_from:
    - data
  #links:
    #- consul
  #ports:
    #- 8384
  restart: always
  mem_limit: 1024m
  environment:
    - MYSQL_ROOT_PASSWORD
    - MYSQL_ALLOW_EMPTY_PASSWORD
#consul:
  #image: gliderlabs/consul-server
  #command: -bootstrap -ui-dir /ui
  #expose:
  #- 8400
  #- 8500
  #- 53/udp
  #restart: always
  #mem_limit: 256m
cloner:
  image: xer0x/triton-mysql-cloner
  volumes_from:
    - data
  links:
    - mysql
  entrypoint:
    # - "top"
    - "/start.sh"
  environment:
    - MYSQL_ROOT_PASSWORD
    - MYSQL_ALLOW_EMPTY_PASSWORD
